### ISSUE TITLE
from maskrcnn_benchmark.config import cfg

### ISSUE THREAD

**Issue by lmplayer** [sadicLiu/mask_rcnn_code#1]
from maskrcnn_benchmark.config import cfg
Please my question: where is cfg? How to get it?

**Comment by sadicLiu** [comment]
give a look at mask_rcnn_code/maskrcnn_benchmark/config/__init__.py

**Comment by yolunghiu** [comment]
@S20180674 give a look at mask_rcnn_code/maskrcnn_benchmark/config/init.py
